import { NextResponse } from 'next/server';
import dbConnect from '@/lib/dbConnect';
import Inquiry from '@/models/Inquiry';
import nodemailer from 'nodemailer';

function isAuthenticated(request) {
  const adminPassword = process.env.ADMIN_PASSWORD || 'admin123';
  const requestPassword = request.headers.get('x-admin-password');
  return requestPassword === adminPassword;
}

// GET /api/inquiries - Fetch all customer leads (Admin Only)
export async function GET(request) {
  try {
    if (!isAuthenticated(request)) {
      return NextResponse.json(
        { success: false, error: 'Unauthorized. Invalid admin password.' },
        { status: 401 }
      );
    }

    await dbConnect();
    const inquiries = await Inquiry.find({}).sort({ createdAt: -1 });
    return NextResponse.json({ success: true, data: inquiries }, { status: 200 });
  } catch (error) {
    return NextResponse.json(
      { success: false, error: error.message },
      { status: 550 }
    );
  }
}

// POST /api/inquiries - Submit a customer lead (Public)
export async function POST(request) {
  try {
    await dbConnect();
    const body = await request.json();
    
    const { name, phone, productNeeded, message } = body;

    if (!name || !phone) {
      return NextResponse.json(
        { success: false, error: 'Name and Phone number are required.' },
        { status: 400 }
      );
    }

    const inquiry = await Inquiry.create({
      name,
      phone,
      productNeeded,
      message,
    });

    // Attempt to send email notification (fails gracefully if SMTP is not configured)
    const smtpHost = process.env.SMTP_HOST;
    const smtpPort = process.env.SMTP_PORT;
    const smtpUser = process.env.SMTP_USER;
    const smtpPass = process.env.SMTP_PASS;
    const targetEmail = process.env.NOTIFICATION_EMAIL;

    if (smtpHost && smtpPort && smtpUser && smtpPass && targetEmail) {
      try {
        const transporter = nodemailer.createTransport({
          host: smtpHost,
          port: parseInt(smtpPort),
          secure: parseInt(smtpPort) === 465,
          auth: {
            user: smtpUser,
            pass: smtpPass,
          },
        });

        const mailOptions = {
          from: `"Ujjwal Iron Leads" <${smtpUser}>`,
          to: targetEmail,
          subject: `🚨 New Web Inquiry: ${name}`,
          text: `You have received a new customer lead on Ujjwal Iron Patna:

Customer Name: ${name}
Phone Number: ${phone}
Product Needed: ${productNeeded || 'Not Specified'}
Message: ${message || 'No additional message'}

Date: ${new Date().toLocaleString()}

Please contact the lead immediately.

---
This email was auto-generated by the Ujjwal Iron website catalog system.`,
        };

        await transporter.sendMail(mailOptions);
      } catch (emailError) {
        console.error('SMTP Mail Dispatch Failed:', emailError.message);
      }
    }

    return NextResponse.json({ success: true, data: inquiry }, { status: 201 });
  } catch (error) {
    return NextResponse.json(
      { success: false, error: error.message },
      { status: 400 }
    );
  }
}
